### ISSUE TITLE
NameError: global name 'Falses' is not defined

### ISSUE THREAD

**Issue by mapooo** [thebotsmith/Excelsior-Milano-raffle#2]
I have edited the code with my details, but when i run it all the tasks spit out this error:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "main.py", line 100, in run
    self.loopThrough()
  File "main.py", line 63, in loopThrough
    r = self.s.get(self.url,headers=self.headers1,verify=Falses)
NameError: global name 'Falses' is not defined`

Otherwise seems like a really cool script, this might just be down to me not having all the python dependencies installed for all I know

edit: my current python version is 2.7.12

**Comment by mapooo** [comment]
My solution was to change "Falses" (line 63) to "False"

I get a huge line of 'list' object has no attribute 'get' but all my threads report that they have successfully finnished.

Im not sure if you want to add me as a contributor, or just change it yourself, I'm still getting used to contributing to github projects
